<?php

/*--------------------------------------------------------------------------*
 *   SHIT:FRAMEWORK commands docker mode
 *--------------------------------------------------------------------------*/

namespace shit;

return array(
    // action                         func   arg    command
    //'docker_glftpd_status' => array('api', 'GET', '/containers/json?filters=' . urlencode('{"name":["^glftpd$"]}')),
    'glftpd_status'         => array('api', 'GET', '/containers/json?filters=' . urlencode('{"name":["^') . '{$gl_ct_name}' . urlencode('$"]}')),
    'glftpd_start'          => array('api', 'POST', '/containers/{$gl_ct_name}/start', ''),
    'glftpd_stop'           => array('api', 'POST', '/containers/{$gl_ct_name}/stop', ''),
    'glftpd_restart'        => array('api', 'POST', '/containers/{$gl_ct_name}/restart', ''),
    'glftpd_kill'           => array('api', 'POST', '/containers/{$gl_ct_name}/kill', ''),
    'docker_top_glftpd'     => array('api', 'GET', '/containers/{$gl_ct_name}/top', null),
    'docker_logs_glftpd'    => array('api', 'GET', '/containers/{$gl_ct_name}/logs?stdout=true&stderr=true', null),
    'docker_tail_glftpd'    => array('api', 'GET', '/containers/{$gl_ct_name}/logs?stdout=true&stderr=true&tail=10', null),
    'docker_inspect_glftpd' => array('api', 'GET', '/containers/{$gl_ct_name}/json', null),
    'docker_create_glftpd'  => array("create", '{$gl_ct_name}', "docker-glftpd:latest", "/glftpd", "1337/tcp", "127.0.0.1", "1337", "shit"),
    'ps_gotty'              => array("exec", '{$gl_ct_name}', '["sh", "-c", "/bin/busybox ps aux|grep \"[gG]otty\""]'),
    'tty_glspy'             => array("exec", '{$gl_ct_name}', '["sh", "-c", "/bin/busybox killall -9 gotty >/dev/null 2>&1; {$bin_dir}/gotty {$bin_dir}/gl_spy -r/glftpd/glftpd.conf >/dev/null 2>&1 &"]'),
    'tty_useredit'          => array("exec", '{$gl_ct_name}', '["sh", "-c", "/bin/busybox killall -9 gotty >/dev/null 2>&1; {$bin_dir}/gotty {$bin_dir}/useredit -r/glftpd/glftpd.conf >/dev/null 2>&1 &"]'),
    'tty_eggdrop'           => array("exec", '{$gl_ct_name}', '["sh", "-c", "/bin/busybox killall -9 gotty >/dev/null 2>&1; {$bin_dir}/gotty /bin/busybox telnet 127.0.0.1 3333 >/dev/null 2>&1 &"]'),
    'tty_pywho'             => array("exec", '{$gl_ct_name}', '["sh", "-c", "/bin/busybox killall -9 gotty >/dev/null 2>&1; {$bin_dir}/gotty {$bin_dir}/pywho >/dev/null 2>&1 &"]'),
    'tty_pyspy'             => array("exec", '{$gl_ct_name}', '["sh", "-c", "/bin/busybox killall -9 gotty >/dev/null 2>&1; {$bin_dir}/gotty {$bin_dir}/spy >/dev/null 2>&1 &"]'),
    'kill_gotty'            => array("exec", '{$gl_ct_name}', '["/bin/busybox", "killall", "-9", "gotty"]'),
    'kill_glspy'            => array("exec", '{$gl_ct_name}', '["/bin/busybox", "killall", "-9", "gl_spy"]'),
    'kill_useredit'         => array("exec", '{$gl_ct_name}', '["/bin/busybox", "killall", "-9", "useredit"]'),
    'pywho'                 => array("exec", '{$gl_ct_name}', '["sh", "-c", "{$bin_dir}/pywho &"]'),
    'passchk'               => array("exec", '{$gl_ct_name}', '["{$bin_dir}/passchk", "{$username}", "{$password}", "/glftpd/etc/passwd"]'),
    'gltool_log'            => array("exec", '{$gl_ct_name}', '["{$bin_dir}/gltool.sh", "-c", "LOGSHOW"]'),
    'gltool_tail'           => array("exec", '{$gl_ct_name}', '["{$bin_dir}/gltool.sh", "-c", "LOGTAIL"]'),
    'users_list'            => array("exec", '{$gl_ct_name}', '["{$bin_dir}/gltool.sh", "-c", "LISTUSERS"]'),
    'users_raw'             => array("exec", '{$gl_ct_name}', '["{$bin_dir}/gltool.sh", "-c", "RAWUSERS"]'),
    'groups_list'           => array("exec", '{$gl_ct_name}', '["{$bin_dir}/gltool.sh", "-c", "LISTGROUPS"]'),
    'groups_raw'            => array("exec", '{$gl_ct_name}', '["{$bin_dir}/gltool.sh", "-c", "RAWGROUPS"]'),
    'pgroups_raw'           => array("exec", '{$gl_ct_name}', '["{$bin_dir}/gltool.sh", "-c", "RAWPGROUPS"]'),
    'ip_list'               => array("exec", '{$gl_ct_name}', '["{$bin_dir}/gltool.sh", "-c", "LISTIP", "-u", "{$username}"]'),
    'ip_raw'                => array("exec", '{$gl_ct_name}', '["{$bin_dir}/gltool.sh", "-c", "RAWIP", "-u", "{$username}"]'),
    'ip_add'                => array("exec", '{$gl_ct_name}', '["{$bin_dir}/gltool.sh", "-c", "ADDIP", "-u", "{$username}", "-i", "{$mask}"]'),
    'ip_del'                => array("exec", '{$gl_ct_name}', '["{$bin_dir}/gltool.sh", "-c", "DELIP", "-u", "{$username}", "-i", "{$mask}"]'),
    'user_add'              => array("exec", '{$gl_ct_name}', '["{$bin_dir}/gltool.sh", "-c", "ADDUSER", "-u", "{$username}", "-p", "{$password}", "-g", "{$group}", "-i", "{$mask}", "-a", "{$gadmin}"]'),
    'user_gadmin'           => array("exec", '{$gl_ct_name}', '["{$bin_dir}/gltool.sh", "-c", "USERGADMIN", "-u", "{$username}", "-g", "{$group}", "-a", "{$gadmin}"]'),
    'user_chgadmin'         => array("exec", '{$gl_ct_name}', '["{$bin_dir}/gltool.sh", "-c", "CHGADMIN", "-u", "{$username}", "-g", "{$group}"]'),
    'user_del'              => array("exec", '{$gl_ct_name}', '["{$bin_dir}/gltool.sh", "-c", "DELUSER", "-u", "{$username}"]'),
    'group_add'             => array("exec", '{$gl_ct_name}', '["{$bin_dir}/gltool.sh", "-c", "ADDGROUP", "-g", "{$group}"]'),
    'group_del'             => array("exec", '{$gl_ct_name}', '["{$bin_dir}/gltool.sh", "-c", "DELGROUP", "-g", "{$group}"]'),
    'group_change'          => array("exec", '{$gl_ct_name}', '["{$bin_dir}/gltool.sh", "-c", "CHGRP", "-u", "{$username}", "-g" "{$group}"]]'),
    'add_user_group'        => array("exec", '{$gl_ct_name}', '["{$bin_dir}/gltool.sh", "-c", "ADDUSERGROUP", "-u", "{$username}", "-g", "{$group}"]'),
    'del_user_group'        => array("exec", '{$gl_ct_name}', '["{$bin_dir}/gltool.sh", "-c", "DELUSERGROUP", "-u", "{$username}", "-g", "{$group}"]'),
    'add_user_pgroup'       => array("exec", '{$gl_ct_name}', '["{$bin_dir}/gltool.sh", "-c", "ADDUSERPROUP", "-u", "{$username}", "-s", "{$pgroup}"]'),
    'del_user_pgroup'       => array("exec", '{$gl_ct_name}', '["{$bin_dir}/gltool.sh", "-c", "DELUSERPGROUP", "-u", "{$username}", "-s", "{$pgroup}"]'),
    'password_change'       => array("exec", '{$gl_ct_name}', '["{$bin_dir}/gltool.sh", "-c", "CHPASS", "-u", "{$username}", "-p", "{$password}"]'),
    'tagline_change'        => array("exec", '{$gl_ct_name}', '["{$bin_dir}/gltool.sh", "-c", "CHTAG", "-u", "{$username}", "-t",  "{$tagline}"]'),
    'flag_add'              => array("exec", '{$gl_ct_name}', '["{$bin_dir}/gltool.sh", "-c", "ADDFLAG", "-u", "{$username}", "-f", "{$flags}"]'),
    'flag_del'              => array("exec", '{$gl_ct_name}', '["{$bin_dir}/gltool.sh", "-c", "DELFLAG", "-u", "{$username}", "-f", "{$flags}"]'),
    'flag_change'           => array("exec", '{$gl_ct_name}', '["{$bin_dir}/gltool.sh", "-c", "CHFLAG", "-u", "{$username}", "-f", "{$flags}"]'),
    'credits_change'        => array("exec", '{$gl_ct_name}', '["{$bin_dir}/gltool.sh", "-c", "CHCREDITS", "-u", "{$username}", "-k", "{$credits}"]'),
    'ratio_change'          => array("exec", '{$gl_ct_name}', '["{$bin_dir}/gltool.sh", "-c", "CHRATIO", "-u", "{$username}", "-r", "{$ratio}""]'),
    'logins_change'         => array("exec", '{$gl_ct_name}', '["{$bin_dir}/gltool.sh", "-c", "CHLOGINS", "-u", "{$username}", "-k", "{$logins}"]'),
    'userfile_raw'          => array("exec", '{$gl_ct_name}', '["{$bin_dir}/gltool.sh", "-c", "RAWUSERFILE", "-u", "{$username}"]'),
    'usersgroups_raw'       => array("exec", '{$gl_ct_name}', '["{$bin_dir}/gltool.sh", "-c", "RAWUSERSGROUPS"]'),
    'userspgroups_raw'      => array("exec", '{$gl_ct_name}', '["{$bin_dir}/gltool.sh", "-c", "RAWUSERSPGROUPS"]'),
    'usergroup_raw'         => array("exec", '{$gl_ct_name}', '["{$bin_dir}/gltool.sh", "-c", "RAWUSERGROUP", "-u", "{$username}"]'),
    'tag_raw'               => array("exec", '{$gl_ct_name}', '["{$bin_dir}/gltool.sh", "-c", "RAWTAG", "-u", "{$username}"]'),
    'flag_raw'              => array("exec", '{$gl_ct_name}', '["{$bin_dir}/gltool.sh", "-c", "RAWFLAG", "-u", "{$username}"]'),
    'creds_raw'             => array("exec", '{$gl_ct_name}', '["{$bin_dir}/gltool.sh", "-c", "RAWCREDS", "-u", "{$username}"]'),
    'reset_user_stats'      => array("exec", '{$gl_ct_name}', '["{$bin_dir}/gltool.sh", "-c", "RESETUSERSTATS", "-u", "{$username}"]'),
    'auth_mode'             => array("exec", '{$web_ct_name}', '["/auth.sh", "{$mode}"]'),
    'auth_user_pass'        => array("exec", 'glftpd-web', '["/auth.sh", "{$mode}", "{$username}", "{$password}"]'),
    'nginx_reload'          => array("exec", '{$web_ct_name}', '["nginx", "-s", "reload"]'),
    'ps_gotty_proc'         => array("exec", '{$gl_ct_name}', '["sh", "-c", "grep -ar [gG]otty /proc/[0-9]*/cmdline"]'),
);
