<?php

/*--------------------------------------------------------------------------*
 *   SHIT:FRAMEWORK commands docker mode
 *--------------------------------------------------------------------------*/

namespace shit;

return array(
    // action                         func   arg    command
    'glftpd_status'         => array("api", "GET", '/containers/json?filters=' . urlencode('{"name":["^glftpd$"]}')),
    'glftpd_start'          => array("api", "POST", '/containers/{$gl_ct}/start', ''),
    'glftpd_stop'           => array("api", "POST", '/containers/{$gl_ct}/stop', ''),
    'glftpd_restart'        => array("api", "POST", '/containers/{$gl_ct}/restart', ''),
    'glftpd_kill'           => array("api", "POST", '/containers/{$gl_ct}/kill', ''),
    'glftpd_top'            => array("api", "GET", '/containers/{$gl_ct}/top', null),
    'glftpd_logs'           => array("api", "GET", '/containers/{$gl_ct}/logs?stdout=true&stderr=true', null),
    'glftpd_tail'           => array("api", "GET", '/containers/{$gl_ct}/logs?stdout=true&stderr=true&tail=10', null),
    'glftpd_inspect'        => array("api", "GET", '/containers/{$gl_ct}/json', null),
    'glftpd_create'         => array("create", "glftpd", "docker-glftpd:latest", "/glftpd", "1337/tcp", "127.0.0.1", "1337", "shit"),
    'ps_gotty'              => array("exec", "glftpd", '["sh", "-c", "busybox ps aux|grep \"[gG]otty\""]'),
    'tty_glspy'             => array("exec", "glftpd", '["sh", "-c", "busybox killall -9 gotty >/dev/null 2>&1; gotty {$bindir}/gl_spy -r/glftpd/glftpd.conf >/dev/null 2>&1 &"]'),
    'tty_useredit'          => array("exec", "glftpd", '["sh", "-c", "busybox killall -9 gotty >/dev/null 2>&1; gotty {$bindir}/useredit -r/glftpd/glftpd.conf >/dev/null 2>&1 &"]'),
    'tty_eggdrop'           => array("exec", "glftpd", '["sh", "-c", "busybox killall -9 gotty >/dev/null 2>&1; gotty busybox telnet localhost 3333 >/dev/null 2>&1 &"]'),
    'tty_pywho'             => array("exec", "glftpd", '["sh", "-c", "busybox killall -9 gotty >/dev/null 2>&1; gotty {$bindir}/pywho >/dev/null 2>&1 &"]'),
    'tty_pyspy'             => array("exec", "glftpd", '["sh", "-c", "busybox killall -9 gotty >/dev/null 2>&1; gotty {$bindir}/spy >/dev/null 2>&1 &"]'),
    'kill_gotty'            => array("exec", "glftpd", '["busybox", "killall", "-9", "gotty"]'),
    'kill_glspy'            => array("exec", "glftpd", '["busybox", "killall", "-9", "gl_spy"]'),
    'kill_useredit'         => array("exec", "glftpd", '["busybox", "killall", "-9", "useredit"]'),
    'pywho'                 => array("exec", "glftpd", '["sh", "-c", "{$bindir}/pywho &"]'),
    'passchk'               => array("exec", "glftpd", '["{$bindir}/passchk", "{$username}", "{$password}", "/glftpd/etc/passwd"]'),
    'gltool_log'            => array("exec", "glftpd", '["{$bindir}/gltool.sh", "-c", "LOGSHOW"]'),
    'gltool_tail'           => array("exec", "glftpd", '["{$bindir}/gltool.sh", "-c", "LOGTAIL"]'),
    'users_list'            => array("exec", "glftpd", '["{$bindir}/gltool.sh", "-c", "LISTUSERS"]'),
    'users_raw'             => array("exec", "glftpd", '["{$bindir}/gltool.sh", "-c", "RAWUSERS"]'),
    'groups_list'           => array("exec", "glftpd", '["{$bindir}/gltool.sh", "-c", "LISTGROUPS"]'),
    'groups_raw'            => array("exec", "glftpd", '["{$bindir}/gltool.sh", "-c", "RAWGROUPS"]'),
    'pgroups_raw'           => array("exec", "glftpd", '["{$bindir}/gltool.sh", "-c", "RAWPGROUPS"]'),
    'ip_list'               => array("exec", "glftpd", '["{$bindir}/gltool.sh", "-c", "LISTIP", "-u", "{$username}"]'),
    'ip_raw'                => array("exec", "glftpd", '["{$bindir}/gltool.sh", "-c", "RAWIP", "-u", "{$username}"]'),
    'ip_add'                => array("exec", "glftpd", '["{$bindir}/gltool.sh", "-c", "ADDIP", "-u", "{$username}", "-i", "{$mask}"]'),
    'ip_del'                => array("exec", "glftpd", '["{$bindir}/gltool.sh", "-c", "DELIP", "-u", "{$username}", "-i", "{$mask}"]'),
    'user_add'              => array("exec", "glftpd", '["{$bindir}/gltool.sh", "-c", "ADDUSER", "-u", "{$username}", "-p", "{$password}", "-g", "{$group}", "-i", "{$mask}", "-a", "{$gadmin}"]'),
    'user_gadmin'           => array("exec", "glftpd", '["{$bindir}/gltool.sh", "-c", "USERGADMIN", "-u", "{$username}", "-g", "{$group}", "-a", "{$gadmin}"]'),
    'user_chgadmin'         => array("exec", "glftpd", '["{$bindir}/gltool.sh", "-c", "CHGADMIN", "-u", "{$username}", "-g", "{$group}"]'),
    'user_del'              => array("exec", "glftpd", '["{$bindir}/gltool.sh", "-c", "DELUSER", "-u", "{$username}"]'),
    'group_add'             => array("exec", "glftpd", '["{$bindir}/gltool.sh", "-c", "ADDGROUP", "-g", "{$group}"]'),
    'group_del'             => array("exec", "glftpd", '["{$bindir}/gltool.sh", "-c", "DELGROUP", "-g", "{$group}"]'),
    'group_change'          => array("exec", "glftpd", '["{$bindir}/gltool.sh", "-c", "CHGRP", "-u", "{$username}", "-g" "{$group}"]]'),
    'add_user_group'        => array("exec", "glftpd", '["{$bindir}/gltool.sh", "-c", "ADDUSERGROUP", "-u", "{$username}", "-g", "{$group}"]'),
    'del_user_group'        => array("exec", "glftpd", '["{$bindir}/gltool.sh", "-c", "DELUSERGROUP", "-u", "{$username}", "-g", "{$group}"]'),
    'add_user_pgroup'       => array("exec", "glftpd", '["{$bindir}/gltool.sh", "-c", "ADDUSERPROUP", "-u", "{$username}", "-s", "{$pgroup}"]'),
    'del_user_pgroup'       => array("exec", "glftpd", '["{$bindir}/gltool.sh", "-c", "DELUSERPGROUP", "-u", "{$username}", "-s", "{$pgroup}"]'),
    'password_change'       => array("exec", "glftpd", '["{$bindir}/gltool.sh", "-c", "CHPASS", "-u", "{$username}", "-p", "{$password}"]'),
    'tagline_change'        => array("exec", "glftpd", '["{$bindir}/gltool.sh", "-c", "CHTAG", "-u", "{$username}", "-t",  "{$tagline}"]'),
    'flag_add'              => array("exec", "glftpd", '["{$bindir}/gltool.sh", "-c", "ADDFLAG", "-u", "{$username}", "-f", "{$flags}"]'),
    'flag_del'              => array("exec", "glftpd", '["{$bindir}/gltool.sh", "-c", "DELFLAG", "-u", "{$username}", "-f", "{$flags}"]'),
    'flag_change'           => array("exec", "glftpd", '["{$bindir}/gltool.sh", "-c", "CHFLAG", "-u", "{$username}", "-f", "{$flags}"]'),
    'credits_change'        => array("exec", "glftpd", '["{$bindir}/gltool.sh", "-c", "CHCREDITS", "-u", "{$username}", "-k", "{$credits}"]'),
    'ratio_change'          => array("exec", "glftpd", '["{$bindir}/gltool.sh", "-c", "CHRATIO", "-u", "{$username}", "-r", "{$ratio}""]'),
    'logins_change'         => array("exec", "glftpd", '["{$bindir}/gltool.sh", "-c", "CHLOGINS", "-u", "{$username}", "-k", "{$logins}"]'),
    'userfile_raw'          => array("exec", "glftpd", '["{$bindir}/gltool.sh", "-c", "RAWUSERFILE", "-u", "{$username}"]'),
    'usersgroups_raw'       => array("exec", "glftpd", '["{$bindir}/gltool.sh", "-c", "RAWUSERSGROUPS"]'),
    'userspgroups_raw'      => array("exec", "glftpd", '["{$bindir}/gltool.sh", "-c", "RAWUSERSPGROUPS"]'),
    'usergroup_raw'         => array("exec", "glftpd", '["{$bindir}/gltool.sh", "-c", "RAWUSERGROUP", "-u", "{$username}"]'),
    'tag_raw'               => array("exec", "glftpd", '["{$bindir}/gltool.sh", "-c", "RAWTAG", "-u", "{$username}"]'),
    'flag_raw'              => array("exec", "glftpd", '["{$bindir}/gltool.sh", "-c", "RAWFLAG", "-u", "{$username}"]'),
    'creds_raw'             => array("exec", "glftpd", '["{$bindir}/gltool.sh", "-c", "RAWCREDS", "-u", "{$username}"]'),
    'reset_user_stats'      => array("exec", "glftpd", '["{$bindir}/gltool.sh", "-c", "RESETUSERSTATS", "-u", "{$username}"]'),
    'nginx_reload'          => array("exec", "glftpd-web", '["nginx", "-s", "reload"]'),

    //'ps_gotty'           => array("exec", "glftpd", '["sh", "-c", "grep -ar [gG]otty /proc/[0-9]*/cmdline"]'),
);
