---

###################
# glftpd-webui-dev
###################
#version: '3'
services:
  # Update this to the name of the service you want to work with in your docker-compose.yml file
  #app:
    # Uncomment if you want to override the service's Dockerfile to one in the .devcontainer 
    # folder. Note that the path of the Dockerfile and context is relative to the *primary* 
    # docker-compose.yml file (the first in the devcontainer.json "dockerComposeFile"
    # array). The sample below assumes your primary file is in the root of your project.
    #
    # build:
    #   context: .
    #   dockerfile: .devcontainer/Dockerfile
    #
    # volumes:
    #   Update this to wherever you want VS Code to mount the folder of your project
    #   - ..:/workspaces:cached
    #
    # Overrides default command so things don't shut down after the process ends.
    # command: /bin/sh -c "while sleep 1000; do :; done"
    #
    # Uncomment the next four lines if you will use a ptrace-based debugger like C++, Go, and Rust.
    # cap_add:
    #   - SYS_PTRACE
    # security_opt:
    #   - seccomp:unconfined

  # always build dev web

  dev-web:
    profiles: [dev]
    build:
      context: .
      cache_from:
        - docker-glftpd-web:latest
      dockerfile: Dockerfile
      # uncomment to set port, auth mode, htpasswd etc
      # args:
      #   - WEBUI_PORT=4043
      #   - WEBUI_AUTH_MODE=basic
      #   - WEBUI_AUTH_USER=notshit
      #   - WEBUI_AUTH_PASS=Othersh1ttyPass
      #extra_hosts: ["host.docker.internal:host-gateway"]
    volumes:
      - ./glftpd/glftpd.conf:/app/glftpd/glftpd.conf
      - ./glftpd/sitebot/eggdrop.conf:/app/glftpd/sitebot/eggdrop.conf
      - ./glftpd/sitebot/pzs-ng/ngBot.conf:/app/glftpd/sitebot/pzs-ng/ngBot.conf
      - ./glftpd/site:/app/glftpd/site
      # devcontainer
      - /var/run/docker.sock:/var/run/docker.sock
      #- ./etc/nginx/http.d:/etc/nginx/http.d:cached
      #- ./etc/nginx/auth.d:/etc/nginx/auth.d:cached
      - ./src/ui:/app:cached
      - ./src/ui/config.php:/app/ui/config.php:cached
      - ./src/auth:/auth:cached
      - ./lib/ui:/app/lib:cached
      - ./lib/auth:/auth/lib:cached
      - ./templates:/app/templates:cached
      - ./assets:/app/assets:cached
      # use local gldir
      # - /jail/glftpd:/glftpd:cached
      # XXX: (dev-test) use systemd from host
      # - /run:/host-run
    ports:
      - 4444:443
    ulimits:
      nofile: { soft: 1024, hard: 1024 }
    #environment:
    #  - WEBUI_AUTH_MODE=both
    # XXX: (dev-test) host systemd needs privileged mode
    #  privileged: true
    # uncomment to use host instead of bridge
    #  network_mode: host
    hostname: glftpd-web
    depends_on: [dev-glftpd]


  # use existing gl image from docker-glftpd

  dev-glftpd:
    profiles: [dev]
    image: docker-glftpd:full
    volumes:
      - source: ./glftpd/site
        target: /glftpd/site
        type: bind
        bind: { create_host_path: false }
      - source: ./glftpd/glftpd.conf
        target: /glftpd/glftpd.conf
        type: bind
        bind: { create_host_path: false }
      - source: ./glftpd/etc
        target: /glftpd/etc
        type: bind
        bind: { create_host_path: false }
      - source: ./glftpd/ftp-data/users
        target: /glftpd/ftp-data/users
        type: bind
        bind: { create_host_path: false }
      - source: ./glftpd/ftp-data/groups
        target: /glftpd/ftp-data/groups
        type: bind
        bind: { create_host_path: false }
      - source: ./glftpd/sitebot
        target: /glftpd/sitebot
        type: bind
        bind: { create_host_path: false }
    # mount gldir from docker-glftpd (instead of symlink)
    #     - ../docker-glftpd/glftpd/site:/glftpd/site:rw
    #     - ../docker-glftpd/glftpd/glftpd.conf:/glftpd/glftpd.conf
    #     - ../docker-glftpd/glftpd/etc:/glftpd/etc
    #     - ../docker-glftpd/glftpd/ftp-data/users:/glftpd/ftp-data/users
    #     - ../docker-glftpd/glftpd/ftp-data/groups:/glftpd/ftp-data/groups
    #     - ../docker-glftpd/glftpd/sitebot:/glftpd/sitebot
    ports:
      - "1337:1337"
      - "3333:3333"
    ulimits:
      nofile: { soft: 1024, hard: 1024 }
    hostname: glftpd


  # workaround to skip profiles from root docker-compose.yml

  #glftpd:
  #  profiles: ['SKIP']
  #  image: ghcr.io/silv3rr/docker-glftpd:full
  #  container_name: skip-glftpd
  #web:
  #  profiles: ['SKIP']
  #  image: ghcr.io/silv3rr/docker-glftpd-web:latest
  #  container_name: skip-glftpd-web

  # skip local-web, use devcontainer instead

  #local-web:
  #  image: docker-glftpd-web:latest
  #  container_name: skip-local-web
