name: "IRC Manual Notification"
on: workflow_dispatch

# git log  --pretty=format:'%an %h commit: %s'

jobs:
  irc-messsage-old:
    runs-on: ubuntu-latest
    steps:
      - name: irc push
        uses: rectalogic/notify-irc@v1
        with:
          channel: "#glhelp"
          server: "irc.choopa.net"
          port: 6667
          tls: false
          nickname: shithub
          message: |-
            silver 000abc commit: foo

